server:
  port: 8765
  
spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    account:
      path: /accounts/**
      serviceId: account-service
      strip-prefix: false
    customer:
      path: /customers/**
      serviceId: customer-service
      strip-prefix: false